# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1053185c77d141383246320cec71bca54cee7d653ee6ab7008f13c61215945849466d9ba07a500bf6dee52397271ea2847d5f341eeb24b07d137a8d0be6169cc

test:
  secret_key_base: 243e501bede65cadee78b82dacacfbea0637bb3b1602dc87c4074bde93e6f721740497c68e2c9fa58ed9b5525fc8127d7cfbfa822f66acb10b51c4bab644f107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
